defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/php-ci:2.x
  working_directory: ~/pantheon_workspace
  environment:

    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/env-vars/
    #
    # PANTHEON_SITE:  Name of the Pantheon site to rebuild
    # PANTHEON_ENV:  Name of the environment on the Pantheon site to rebuild
    # TERMINUS_TOKEN: The Pantheon machine token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # DEFAULT_ACCOUNT_PASS:    The admin password to use when installing.
    # DEFAULT_ACCOUNT_MAIL:    The email address to give the admin when installing.
    # DEFAULT_ACCOUNT_NAME:    The email address to give the admin when installing.
    # APIGEE_ORG: Name of the apigee organization to connect to
    # APIGEE_USER: Apigee username to use to connect
    # APIGEE_PASS: Apigee user password
    #=========================================================================

    TZ: "/usr/share/zoneinfo/America/New_York"
    TERM: dumb
    TERMINUS_HIDE_UPDATE_MESSAGE: 1

version: 2
jobs:
    # Note that we do more work on the Drupal 8 + GitHub test than in other permutations.
    # We test creating a PR and merging it to master here, but omit those tests
    # elsewhere in the interest of saving testing time.
    build_d8_kickstart_test_site:
        <<: *defaults
        resource_class: large
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "08:d9:e4:32:97:d1:b9:0f:06:c8:e4:11:3f:f4:e7:1d"
            - checkout
            - run:
                name: Run the install scripts
                command: ./scripts/setup_install.sh
workflows:
  version: 2
  build_at_12_am:
    triggers:
      - schedule:
          cron: "0 0 * * *" #trigger at midnight
          filters:
            branches:
              only:
                - master
    jobs:
      - build_d8_kickstart_test_site
  build_at_8_am:
    triggers:
      - schedule:
          cron: "0 10 * * *" #trigger at 8 am
          filters:
            branches:
              only:
                - master
    jobs:
      - build_d8_kickstart_test_site
  build_at_12_pm:
    triggers:
      - schedule:
          cron: "0 12 * * *" #trigger at 12 pm
          filters:
            branches:
              only:
                - master
    jobs:
      - build_d8_kickstart_test_site
  build_at_4_pm:
    triggers:
      - schedule:
          cron: "0 16 * * *" #trigger at 4 pm
          filters:
            branches:
              only:
                - master
    jobs:
      - build_d8_kickstart_test_site
  build_at_8_pm:
    triggers:
      - schedule:
          cron: "0 20 * * *" #trigger at 8 pm
          filters:
            branches:
              only:
                - master
    jobs:
      - build_d8_kickstart_test_site