defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/php-ci:2.x
  working_directory: ~/pantheon_workspace
  environment:

    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/env-vars/
    #
    # PANTHEON_SITE:  Name of the Pantheon site to rebuild
    # PANTHEON_ENV:  Name of the environment on the Pantheon site to rebuild
    # TERMINUS_TOKEN: The Pantheon machine token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # DEFAULT_ACCOUNT_PASS:    The admin password to use when installing.
    # DEFAULT_ACCOUNT_MAIL:    The email address to give the admin when installing.
    # DEFAULT_ACCOUNT_NAME:    The email address to give the admin when installing.
    # APIGEE_ORG: Name of the apigee organization to connect to
    # APIGEE_USER: Apigee username to use to connect
    # APIGEE_PASS: Apigee user password
    #=========================================================================

    TZ: "/usr/share/zoneinfo/America/New_York"
    TERM: dumb
    TERMINUS_HIDE_UPDATE_MESSAGE: 1

version: 2
jobs:
    # Note that we do more work on the Drupal 8 + GitHub test than in other permutations.
    # We test creating a PR and merging it to master here, but omit those tests
    # elsewhere in the interest of saving testing time.
    build_d8_ci_latest:
        <<: *defaults
        resource_class: large
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "08:d9:e4:32:97:d1:b9:0f:06:c8:e4:11:3f:f4:e7:1d"
            - checkout
            - run:
                name: Run the install scripts
                command: ./scripts/setup_install.sh ci-latest
    build_d8_devteams:
      <<: *defaults
      resource_class: large
      steps:
        - add_ssh_keys:
            fingerprints:
              - "08:d9:e4:32:97:d1:b9:0f:06:c8:e4:11:3f:f4:e7:1d"
        - checkout
        - run:
            name: Run the install scripts
            command: ./scripts/setup_install.sh devteams
        - run:
            name: Install the apigee_edge_teams module
            command: terminus drush ${PANTHEON_SITE}.devteams -- en apigee_edge_teams -y
        - run:
            name: Clear caches
            command: terminus env:clear-cache ${PANTHEON_SITE}.devteams
    build_d8_mint:
      <<: *defaults
      resource_class: large
      steps:
        - add_ssh_keys:
            fingerprints:
              - "08:d9:e4:32:97:d1:b9:0f:06:c8:e4:11:3f:f4:e7:1d"
        - checkout
        - run:
            name: Run the install scripts
            command: ./scripts/setup_install.sh mint $APIGEE_MINT_ORG
        - run:
            name: Install the apigee_edge_teams module
            command: terminus drush ${PANTHEON_SITE}.mint -- en apigee_m10n -y
        - run:
            name: Clear caches
            command: terminus env:clear-cache ${PANTHEON_SITE}.mint
    build_d8_google_auth_branch:
      <<: *defaults
      resource_class: large
      steps:
        - add_ssh_keys:
            fingerprints:
              - "08:d9:e4:32:97:d1:b9:0f:06:c8:e4:11:3f:f4:e7:1d"
        - checkout
        - run:
            name: Run the install scripts
            command: ./scripts/setup_install.sh gauth
        - run:
            name: Install the google login module
            command: terminus drush ${PANTHEON_SITE}.gauth -- en social_auth_google -y
        - run:
            name: Set the client id for Google Auth
            command: terminus drush ${PANTHEON_SITE}.gauth -q -- config:set social_auth_google.settings client_id "$GAUTH_CLIENT_ID"
        - run:
            name: Set the client secret for Google Auth
            command: terminus drush ${PANTHEON_SITE}.gauth -q -- config:set social_auth_google.settings client_secret "$GAUTH_CLIENT_SECRET"

workflows:
  version: 2
  rebuild_every4_hours:
    triggers:
      - schedule:
          cron: "0 4 * * *" #trigger at 12 am EST
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 8 * * *" #trigger at 4 am EST
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 12 * * *" #trigger at 8 am EST
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 16 * * *" #trigger at 12 pm EST
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 20 * * *" #trigger at 4 pm EST
          filters:
            branches:
              only:
                - master
      - schedule:
          cron: "0 0 * * *" #trigger 8 pm EST
          filters:
            branches:
              only:
                - master
    jobs:
      - build_d8_ci_latest
  rebuild_on_demand:
    jobs:
      - build_d8_devteams
      - build_d8_google_auth_branch
      - build_d8_mint